In [1]:
import numpy as np


### 1. Create a null vector of size 10 but the fifth value which is 1.


In [5]:
null_vector  = np.zeros(10, dtype='int8')
null_vector[4] = 1
print(null_vector)

[0 0 0 0 1 0 0 0 0 0]


### 2. Create a vector with values ranging from 10 to 49.



In [108]:
a,b = input(" Enter the Low and High of the  Vector range ").split(",")
vec1 = np.random.randint(10,50,size=(int(a),int(b)))
vec = vec1.ravel().copy()

print( " Vector of the Specified Range: ", vec)


 Enter the Low and High of the  Vector range 1,4
 Vector of the Specified Range:  [31 46 34 36]


### 3. Create a 3x3 matrix with values ranging from 0 to 8


In [40]:
array1  = np.arange(9).reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 4. Find indices of non-zero elements from [1,2,0,0,4,0]


In [53]:
vec2 = np.array([1,2,0,0,4,0])
l = []
for i in range(len(vec2)):
    if vec2[i] != 0:
        l.append(i)
    else:
        pass
print(" The Non-Zero Elements Indices: ", *l)    
        

 The Non-Zero Elements Indices:  0 1 4


### 5. Create a 10x10 array with random values and find the minimum and maximum values.


In [107]:
#np.random.seed(4)

array2 = np.random.randint(1,1000,size=(10,10))
print(array2)

print(array2.min()) 
print(array2.max())

[[894 513 912 525 162 216 707 320 460 396]
 [774 106 769 425  24 245 529 538 776 350]
 [207 757 709 280 490 515 603 640  52 472]
 [776 208 372 258 970 200 607 953 489 490]
 [777 933 271 107 437 222   8 970 842 229]
 [308 105 508  39 565 697 697 750 667 236]
 [119 751  37 613 238  43 186 712 275 268]
 [342 690 696 446  29  36 177 706 331  63]
 [408 341 312 959 625 603 530 225 988 151]
 [484 579 239 749 394 608 964 770 617 516]]
8
988


### 6. Create a random vector of size 30 and find the mean value.


In [106]:
vec3 = np.random.ranf(30)*100
print(vec3.round())
print( " Mean of the Array: ",vec3.mean())


#print(np.average(vec3))

[12. 53. 83. 60. 40.  2. 26. 60. 69. 33. 20. 77.  9. 42. 62. 51.  5. 21.
 17. 51. 21. 75.  9. 39. 88. 95. 31. 21.  2. 70.]
 Mean of the Array:  41.437144901887535
